name: Deploy

on:
  push:
    branches:
      - main

jobs:
  blog:
    name: awful.software
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.89.0"
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: awful.software
          folder: public
